-- 🚀 CONTINUE ADDING LESSONS - PART 2: FUNCTIONS, LISTS, LOOPS, STRINGS
-- Run this after ADD_50_LESSONS.sql to reach 60+ total lessons

-- FUNCTIONS & MODULES SECTION (8 lessons)
INSERT INTO lessons (id, title, description, difficulty, xp_reward, order_index, section_id, content, lesson_type, estimated_minutes) VALUES
('40000000-0000-0000-0000-000000000001', 'Creating Functions', 'Learn to define and use functions', 'intermediate', 25, 1, '00000000-0000-0000-0000-000000000004',
'[{"type": "text", "content": "Functions are reusable blocks of code that perform specific tasks. Define them with def keyword: def function_name(parameters): # function body. Use return to send values back."}, {"type": "code", "question": "Create a function that calculates the area of a rectangle', "starterCode": "def rectangle_area(length, width):\n    return length * width\n\n# Test the function\narea = rectangle_area(5, 3)\nprint(f\"Area: {area}\")", "solution": "def rectangle_area(length, width):\n    return length * width\n\narea = rectangle_area(5, 3)\nprint(f\"Area: {area}\")", "hints": ["Define function with def keyword", "Include parameters for length and width", "Use return to send back the result"]}]',
'code', 20),

('40000000-0000-0000-0000-000000000002', 'Function Parameters', 'Passing data to functions', 'intermediate', 28, 2, '00000000-0000-0000-0000-000000000004',
'[{"type": "text", "content": "Functions can accept parameters (positional, keyword, default). Positional parameters are passed by position, keyword parameters by name, and default parameters have fallback values."}, {"type": "code", "question": "Create a function with positional, keyword, and default parameters', "starterCode": "def greet(name, greeting=\"Hello\", punctuation=\"!\"):\n    return f\"{greeting}, {name}{punctuation}\"\n\n# Test with different arguments\nprint(greet(\"Alice\"))\nprint(greet(\"Bob\", greeting=\"Hi\"))\nprint(greet(\"Charlie\", punctuation=\".\"))", "solution": "def greet(name, greeting=\"Hello\", punctuation=\"!\"):\n    return f\"{greeting}, {name}{punctuation}\"\n\nprint(greet(\"Alice\"))\nprint(greet(\"Bob\", greeting=\"Hi\"))\nprint(greet(\"Charlie\", punctuation=\".\"))", "hints": ["Default parameters have fallback values", "Keyword parameters are passed with name=value", "Order matters for positional parameters"]}]',
'code', 18),

('40000000-0000-0000-0000-000000000003', 'Return Values', "Understanding what functions return", 'intermediate', 22, 3, '00000000-0000-0000-0000-000000000004',
'[{"type": "text", "content": "Functions can return values using return. They can return single values, multiple values (as tuples), or nothing (None). You can unpack multiple return values into multiple variables."}, {"type": "code", "question": "Create a function that returns both sum and average of numbers', "starterCode": "def calculate_stats(numbers):\n    total = sum(numbers)\n    average = total / len(numbers)\n    return total, average\n\n# Unpack return values\nnumbers = [1, 2, 3, 4, 5]\ntotal, avg = calculate_stats(numbers)\nprint(f\"Total: {total}, Average: {avg}\")", "solution": "def calculate_stats(numbers):\n    total = sum(numbers)\n    average = total / len(numbers)\n    return total, average\n\nnumbers = [1, 2, 3, 4, 5]\ntotal, avg = calculate_stats(numbers)\nprint(f\"Total: {total}, Average: {avg}\")", "hints": ["Multiple values are returned as tuples", "Unpack with: var1, var2 = function()", "Each return value goes to its variable"]}]',
'code', 15),

('40000000-0000-0000-0000-000000000004', 'Scope and Lifetime', 'Understanding variable scope in functions', 'intermediate', 24, 4, '00000000-0000-0000-0000-000000000004',
'[{"type": "text", "content": "Variable scope determines where variables can be accessed: Local (inside function), Global (outside function), Built-in (Python built-ins). Use global keyword to modify global variables inside functions."}, {"type": "multiple-choice", "question": "What happens when you try to access a local variable outside its function?", "options": ["It works fine", "You get a NameError", "It becomes global automatically", "Python creates a new variable"], "correctAnswer": "You get a NameError", "explanation": "Local variables only exist within the function they\'re defined in. Accessing them outside results in a NameError because they don\'t exist in that scope."}]',
'multiple-choice', 12),

('40000000-0000-0000-0000-000000000005', 'Lambda Functions', 'Writing anonymous functions with lambda', 'intermediate', 20, 5, '00000000-0000-0000-0000-000000000004',
'[{"type": "text", "content": "Lambda functions are small, anonymous functions: lambda arguments: expression. Useful for short operations, often used with map(), filter(), sorted(), and as arguments to other functions."}, {"type": "code", "question": "Use lambda functions with map() and filter()', "starterCode": "numbers = [1, 2, 3, 4, 5]\n\n# Double each number using lambda with map\ndoubled = list(map(lambda x: x * 2, numbers))\nprint(f\"Doubled: {doubled}\")\n\n# Filter even numbers using lambda with filter\nevens = list(filter(lambda x: x % 2 == 0, numbers))\nprint(f\"Even numbers: {evens}\")", "solution": "numbers = [1, 2, 3, 4, 5]\ndoubled = list(map(lambda x: x * 2, numbers))\nprint(f\"Doubled: {doubled}\")\nevens = list(filter(lambda x: x % 2 == 0, numbers))\nprint(f\"Even numbers: {evens}\")", "hints": ["lambda x: expression creates anonymous function", "map() applies function to all items", "filter() keeps items where function returns True"]}]',
'code', 15),

('40000000-0000-0000-0000-000000000006', 'Importing Modules', 'Using external code with imports', 'intermediate', 26, 6, '00000000-0000-0000-0000-000000000004',
'[{"type": "text", "content": "Modules are Python files (.py) that contain functions, classes, and variables. Import them to reuse code: import module, from module import function, import module as alias."}, {"type": "code", "question": "Import and use math module functions', "starterCode": "import math\n\n# Use various math functions\nprint(f\"Pi: {math.pi}\")\nprint(f\"Square root of 16: {math.sqrt(16)}\")\nprint(f\"2^10: {math.pow(2, 10)}\")\nprint(f\"Factorial of 5: {math.factorial(5)}\")", "solution": "import math\nprint(f\"Pi: {math.pi}\")\nprint(f\"Square root of 16: {math.sqrt(16)}\")\nprint(f\"2^10: {math.pow(2, 10)}\")\nprint(f\"Factorial of 5: {math.factorial(5)}\")", "hints": ["Import statements go at the top of the file", "Access module functions with module.function()", "math module provides many mathematical functions"]}]',
'code', 12),

('40000000-0000-0000-0000-000000000007', 'Creating Your Own Modules', 'Organizing code into reusable modules', 'intermediate', 28, 7, '00000000-0000-0000-0000-000000000004',
'[{"type": "text", "content": "Create your own modules by saving Python code in .py files. Module name = filename. You can import functions, classes, and variables from your own modules just like built-in ones."}, {"type": "multiple-choice", "question": "If you save a file named \"calculator.py\", how would you import a function called add from it?", "options": ["import calculator.add", "from calculator import add", "import add from calculator", "from add import calculator"], "correctAnswer": "from calculator import add", "explanation": "Use \"from module_name import function_name\" to import specific functions. The module name is the filename without the .py extension."}]',
'multiple-choice', 10),

('40000000-0000-0000-0000-000000000008', 'Function Best Practices', 'Writing clean, reusable functions', 'intermediate', 18, 8, '00000000-0000-0000-0000-000000000004',
'[{"type": "text", "content": "Best practices for functions: Single responsibility (do one thing well), descriptive names, proper documentation (docstrings), appropriate length, handle errors gracefully, use type hints for clarity."}, {"type": "code", "question": "Rewrite a function with best practices including docstring and type hints', "starterCode": "def calculate_discount(price, discount_percent):\n    \"\"\"Calculate discounted price.\n    \n    Args:\n        price (float): Original price\n        discount_percent (float): Discount percentage (0-100)\n    \n    Returns:\n        float: Discounted price\n    \"\"\"\n    if not 0 <= discount_percent <= 100:\n        raise ValueError(\"Discount must be between 0 and 100\")\n    \n    return price * (1 - discount_percent / 100)\n\n# Test the function\ndiscounted_price = calculate_discount(100, 20)\nprint(f\"Discounted price: ${discounted_price:.2f}\")", "solution": "def calculate_discount(price: float, discount_percent: float) -> float:\n    \"\"\"Calculate discounted price.\n    \n    Args:\n        price (float): Original price\n        discount_percent (float): Discount percentage (0-100)\n    \n    Returns:\n        float: Discounted price\n    \"\"\"\n    if not 0 <= discount_percent <= 100:\n        raise ValueError(\"Discount must be between 0 and 100\")\n    return price * (1 - discount_percent / 100)\n\ndiscounted_price = calculate_discount(100, 20)\nprint(f\"Discounted price: ${discounted_price:.2f}\")", "hints": ["Use docstrings in triple quotes", "Add type hints: parameter: type", "Arrow -> for return type", "Validate inputs and raise errors"]}]',
'code', 20),

-- LISTS & DATA STRUCTURES SECTION (8 lessons)
('50000000-0000-0000-0000-000000000001', 'Python Lists', 'Working with lists in Python', 'intermediate', 25, 1, '00000000-0000-0000-0000-000000000005',
'[{"type": "text", "content": "Lists are ordered, mutable collections of items. Create with square brackets: my_list = [1, 2, 3]. Lists can contain mixed data types and are indexed starting from 0."}, {"type": "code", "question": "Create a shopping list and perform basic operations', "starterCode": "# Create and manipulate a shopping list\nshopping_list = [\"milk\", \"bread\", \"eggs\"]\n\n# Add items\nshopping_list.append(\"cheese\")\nshopping_list.insert(1, \"butter\")\n\n# Remove an item\nshopping_list.remove(\"bread\")\n\n# Access items\nfirst_item = shopping_list[0]\nlast_item = shopping_list[-1]\n\nprint(f\"List: {shopping_list}\")\nprint(f\"First: {first_item}, Last: {last_item}\")", "solution": "shopping_list = [\"milk\", \"bread\", \"eggs\"]\nshopping_list.append(\"cheese\")\nshopping_list.insert(1, \"butter\")\nshopping_list.remove(\"bread\")\nfirst_item = shopping_list[0]\nlast_item = shopping_list[-1]\nprint(f\"List: {shopping_list}\")\nprint(f\"First: {first_item}, Last: {last_item}\")", "hints": ["append() adds to end", "insert() adds at specific index", "remove() removes first occurrence", "[-1] accesses last item"]}]',
'code', 20),

('50000000-0000-0000-0000-000000000002', 'List Operations', 'Common list operations and methods', 'intermediate', 30, 2, '00000000-0000-0000-0000-000000000005',
'[{"type": "text", "content": "List methods: append(), extend(), insert(), remove(), pop(), clear(), index(), count(), sort(), reverse(), copy(). List operations: concatenation (+), repetition (*), membership (in), length (len())."}, {"type": "multiple-choice", "question": "What is the difference between append() and extend()?", "options": ["They are the same", "append() adds one item, extend() adds multiple items", "append() removes items, extend() adds items", "append() works on strings only"], "correctAnswer": "append() adds one item, extend() adds multiple items", "explanation": "append() adds a single item to the end, while extend() adds all items from an iterable (like another list) to the end."}]',
'multiple-choice', 15),

('50000000-0000-0000-0000-000000000003', 'List Slicing', 'Extracting portions of lists', 'intermediate', 22, 3, '00000000-0000-0000-0000-000000000005',
'[{"type": "text", "content": "List slicing syntax: list[start:stop:step]. start is inclusive, stop is exclusive, step is increment. Omit values for defaults: [:] (all), [start:] (from start to end), [:end] (from beginning to end)."}, {"type": "code", "question": "Practice different list slicing operations', "starterCode": "numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n\n# Different slicing operations\nprint(f\"All: {numbers[:]}\")\nprint(f\"First 3: {numbers[:3]}\")\nprint(f\"Last 3: {numbers[-3:]}\")\nprint(f\"Middle (3-6): {numbers[3:7]}\")\nprint(f\"Every other: {numbers[::2]}\")\nprint(f\"Reverse: {numbers[::-1]}\")", "solution": "numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\nprint(f\"All: {numbers[:]}\")\nprint(f\"First 3: {numbers[:3]}\")\nprint(f\"Last 3: {numbers[-3:]}\")\nprint(f\"Middle (3-6): {numbers[3:7]}\")\nprint(f\"Every other: {numbers[::2]}\")\nprint(f\"Reverse: {numbers[::-1]}\")", "hints": ["[:end] gets items before end index", "[start:] gets items from start index", "[::step] uses step for selection", "[-1] as step reverses the list"]}]',
'code', 18),

('50000000-0000-0000-0000-000000000004', 'List Comprehensions', 'Creating lists with concise syntax', 'intermediate', 28, 4, '00000000-0000-0000-0000-000000000005',
'[{"type": "text", "content": "List comprehensions provide concise way to create lists: [expression for item in iterable if condition]. More readable and often faster than equivalent for loops."}, {"type": "code", "question": "Use list comprehensions to create various lists', "starterCode": "# Basic list comprehension\nsquares = [x**2 for x in range(10)]\nprint(f\"Squares: {squares}\")\n\n# With condition\nevens = [x for x in range(20) if x % 2 == 0]\nprint(f\"Even numbers: {evens}\")\n\n# Nested comprehension\nmatrix = [[i*j for j in range(3)] for i in range(3)]\nprint(f\"3x3 multiplication table: {matrix}\")", "solution": "squares = [x**2 for x in range(10)]\nprint(f\"Squares: {squares}\")\nevens = [x for x in range(20) if x % 2 == 0]\nprint(f\"Even numbers: {evens}\")\nmatrix = [[i*j for j in range(3)] for i in range(3)]\nprint(f\"3x3 multiplication table: {matrix}\")", "hints": ["Expression comes first, then for loop", "Add if condition at end for filtering", "Nest comprehensions for 2D structures"]}]',
'code', 20),

('50000000-0000-0000-0000-000000000005', 'Tuples and Sets', 'Other important data structures', 'intermediate', 24, 5, '00000000-0000-0000-0000-000000000005',
'[{"type": "text", "content": "Tuples: ordered, immutable collections (use parentheses). Sets: unordered collections of unique items (use curly braces or set()). Tuples are hashable, sets are great for membership testing and removing duplicates."}, {"type": "code", "question": "Work with tuples and sets', "starterCode": "# Tuple operations\npoint = (3, 4)\nx, y = point  # Tuple unpacking\nprint(f\"Point: ({x}, {y})\")\n\n# Set operations\nnumbers = [1, 2, 2, 3, 3, 4, 4, 5]\nunique_numbers = set(numbers)\nprint(f\"Unique numbers: {unique_numbers}\")\n\n# Set operations\nset_a = {1, 2, 3, 4}\nset_b = {3, 4, 5, 6}\nprint(f\"Union: {set_a | set_b}\")\nprint(f\"Intersection: {set_a & set_b}\")\nprint(f\"Difference: {set_a - set_b}\")", "solution": "point = (3, 4)\nx, y = point\nprint(f\"Point: ({x}, {y})\")\nnumbers = [1, 2, 2, 3, 3, 4, 4, 5]\nunique_numbers = set(numbers)\nprint(f\"Unique numbers: {unique_numbers}\")\nset_a = {1, 2, 3, 4}\nset_b = {3, 4, 5, 6}\nprint(f\"Union: {set_a | set_b}\")\nprint(f\"Intersection: {set_a & set_b}\")\nprint(f\"Difference: {set_a - set_b}\")", "hints": ["Tuples use parentheses, are immutable", "Sets use curly braces, contain unique items", "| is union, & is intersection, - is difference", "Tuple unpacking: a, b = tuple"]}]',
'code', 18),

('50000000-0000-0000-0000-000000000006', 'Dictionaries', 'Key-value pairs in Python', 'intermediate', 26, 6, '00000000-0000-0000-0000-000000000005',
'[{"type": "text", "content": "Dictionaries store key-value pairs: {key: value}. Keys must be hashable (strings, numbers, tuples). Values can be any type. Access values with square brackets: dict[key]."}, {"type": "code", "question": "Create and manipulate a student dictionary', "starterCode": "# Create student dictionary\nstudent = {\n    \"name\": \"Alice\",\n    \"age\": 20,\n    \"grades\": [85, 92, 78],\n    \"active\": True\n}\n\n# Access and modify data\nprint(f\"Student name: {student[\\\"name\\\"]}\")\nprint(f\"Average grade: {sum(student[\\\"grades\\\"]) / len(student[\\\"grades\\\"]):.1f}\")\n\n# Add new key-value pair\nstudent[\\\"major\\\"] = \"Computer Science\"\n\n# Update existing value\nstudent[\\\"age\\\"] = 21\n\nprint(f\"Updated student: {student}\")", "solution": "student = {\n    \"name\": \"Alice\",\n    \"age\": 20,\n    \"grades\": [85, 92, 78],\n    \"active\": True\n}\nprint(f\"Student name: {student[\\\"name\\\"]}\")\nprint(f\"Average grade: {sum(student[\\\"grades\\\"]) / len(student[\\\"grades\\\"]):.1f}\")\nstudent[\\\"major\\\"] = \"Computer Science\"\nstudent[\\\"age\\\"] = 21\nprint(f\"Updated student: {student}\")", "hints": ["Access values with dict[key]", "Add new pairs with dict[new_key] = value", "Update existing pairs the same way", "Use quotes for string keys"]}]',
'code', 20),

('50000000-0000-0000-0000-000000000007', 'Dictionary Methods', 'Working with dictionary operations', 'intermediate', 22, 7, '00000000-0000-0000-0000-000000000005',
'[{"type": "text", "content": "Dictionary methods: keys(), values(), items(), get(), update(), pop(), clear(), popitem(), setdefault(), copy(). Methods for checking membership, merging dictionaries, and safe value access."}, {"type": "code", "question": "Use dictionary methods to analyze data', "starterCode": "inventory = {\n    \"apples\": 10,\n    \"bananas\": 5,\n    \"oranges\": 8,\n    \"pears\": 3\n}\n\n# Get all keys, values, and items\nprint(f\"Fruits available: {list(inventory.keys())}\")\nprint(f\"Quantities: {list(inventory.values())}\")\n\n# Safe access with get()\ncherries = inventory.get(\"cherries\", 0)\nprint(f\"Cherries: {cherries}\")\n\n# Update inventory\ninventory.update({\"grapes\": 12, \"apples\": 15})\nprint(f\"Updated inventory: {inventory}\")", "solution": "inventory = {\n    \"apples\": 10,\n    \"bananas\": 5,\n    \"oranges\": 8,\n    \"pears\": 3\n}\nprint(f\"Fruits available: {list(inventory.keys())}\")\nprint(f\"Quantities: {list(inventory.values())}\")\ncherries = inventory.get(\"cherries\", 0)\nprint(f\"Cherries: {cherries}\")\ninventory.update({\"grapes\": 12, \"apples\": 15})\nprint(f\"Updated inventory: {inventory}\")", "hints": ["get() safely returns default if key missing", "keys() returns dictionary keys", "values() returns dictionary values", "update() merges dictionaries"]}]',
'code', 15),

('50000000-0000-0000-0000-000000000008', 'Data Structure Comparison', 'Choosing the right data structure', 'intermediate', 20, 8, '00000000-0000-0000-0000-000000000005',
'[{"type": "text", "content": "Choose data structures based on needs: List (ordered, changeable collection), Tuple (ordered, immutable), Set (unique items, fast membership), Dictionary (key-value mapping, fast lookup by key)."}, {"type": "multiple-choice", "question": "When should you use a set instead of a list?", "options": ["When you need to maintain order", "When you need unique items and fast membership testing", "When you need to store key-value pairs", "When you need to modify items frequently"], "correctAnswer": "When you need unique items and fast membership testing", "explanation": "Sets automatically enforce uniqueness and provide O(1) membership testing, making them perfect for collections of unique items where you\'ll frequently check if an item exists."}]',
'multiple-choice', 12);

SELECT 'SUCCESS: 40 lessons added! 20 more lessons coming in Part 3...' as message,
       COUNT(*) as total_lessons_added
FROM lessons;