-- 🚀 FINAL LESSON ADDITION - PART 3: LOOPS, STRINGS, FILES, ERRORS, OOP
-- Run this after Parts 1 & 2 to complete the 60+ lesson library

-- LOOPS & ITERATION SECTION (8 lessons)
INSERT INTO lessons (id, title, description, difficulty, xp_reward, order_index, section_id, content, lesson_type, estimated_minutes) VALUES
('60000000-0000-0000-0000-000000000001', 'For Loops', 'Repeating actions with for loops', 'intermediate', 25, 1, '00000000-0000-0000-0000-000000000006',
'[{"type": "text", "content": "For loops iterate over sequences (lists, tuples, strings, ranges). Syntax: for item in sequence: # code block. Use range() for numeric iteration: range(start, stop, step)."}, {"type": "code", "question": "Print numbers 1-10 and their squares', "starterCode": "for i in range(1, 11):\n    square = i ** 2\n    print(f\"{i} squared is {square}\")", "solution": "for i in range(1, 11):\n    square = i ** 2\n    print(f\"{i} squared is {square}\")", "hints": ["range(1, 11) goes from 1 to 10", "** operator is exponentiation", "f-strings make output readable"]}]',
'code', 15),

('60000000-0000-0000-0000-000000000002', 'While Loops', 'Looping based on conditions', 'intermediate', 28, 2, '00000000-0000-0000-0000-000000000006',
'[{"type": "text", "content": "While loops continue as long as a condition is True: while condition: # code block. Be careful with infinite loops! Use break to exit early, continue to skip to next iteration."}, {"type": "code", "question": "Create a countdown timer using while loop', "starterCode": "countdown = 5\nwhile countdown > 0:\n    print(f\"T-minus {countdown}...\")\n    countdown -= 1  # Decrement\n    \nprint(\"Liftoff! 🚀\")", "solution": "countdown = 5\nwhile countdown > 0:\n    print(f\"T-minus {countdown}...\")\n    countdown -= 1\nprint(\"Liftoff! 🚀\")", "hints": ["Decrement counter to avoid infinite loop", "> 0 means while positive numbers", "-= subtracts and assigns in one step"]}]',
'code', 12),

('60000000-0000-0000-0000-000000000003', 'Loop Control', 'Using break and continue statements', 'intermediate', 22, 3, '00000000-0000-0000-0000-000000000006',
'[{"type": "text", "content": "Loop control statements: break (exits loop immediately), continue (skips current iteration, goes to next), else clause (executes when loop completes normally without break)."}, {"type": "code", "question": "Find first number divisible by 7 and 3 between 1-100', "starterCode": "for i in range(1, 101):\n    if i % 7 == 0 and i % 3 == 0:\n        print(f\"First number divisible by 7 and 3: {i}\")\n        break", "solution": "for i in range(1, 101):\n    if i % 7 == 0 and i % 3 == 0:\n        print(f\"First number divisible by 7 and 3: {i}\")\n        break", "hints": ["% operator gives remainder", "0 remainder means divisible", "break stops the loop when found"]}]',
'code', 10),

('60000000-0000-0000-0000-000000000004', 'Nested Loops', 'Loops inside other loops', 'intermediate', 30, 4, '00000000-0000-0000-0000-000000000006',
'[{"type": "text", "content": "Nested loops have one loop inside another. Outer loop runs completely for each iteration of inner loop. Common for 2D arrays, matrices, grid patterns. Use proper indentation for each level."}, {"type": "code", "question": "Create a multiplication table using nested loops', "starterCode": "for i in range(1, 6):  # 1 to 5\n    for j in range(1, 6):\n        product = i * j\n        print(f\"{i:2} x {j:2} = {product:2}\", end=\"  \")\n    print()  # New line after each row", "solution": "for i in range(1, 6):\n    for j in range(1, 6):\n        product = i * j\n        print(f\"{i:2} x {j:2} = {product:2}\", end=\"  \")\n    print()", "hints": ["Outer loop controls rows", "Inner loop controls columns", "end=\"  \" keeps on same line", "print() with no args adds newline"]}]',
'code', 18),

('60000000-0000-0000-0000-000000000005', 'List Comprehensions vs Loops', 'When to use each approach', 'intermediate', 26, 5, '00000000-0000-0000-0000-000000000006',
'[{"type": "text", "content": "List comprehensions are more concise and often faster for simple transformations. Traditional loops are better for complex logic, multiple statements, or when side effects are needed."}, {"type": "code", "question": "Convert between loops and list comprehensions', "starterCode": "numbers = [1, 2, 3, 4, 5]\n\n# Traditional loop\ndoubled_traditional = []\nfor num in numbers:\n    if num % 2 == 1:  # Only odd numbers\n        doubled_traditional.append(num * 2)\n\n# List comprehension\ndoubled_comp = [num * 2 for num in numbers if num % 2 == 1]\n\nprint(f\"Traditional: {doubled_traditional}\")\nprint(f\"Comprehension: {doubled_comp}\")", "solution": "numbers = [1, 2, 3, 4, 5]\ndoubled_traditional = []\nfor num in numbers:\n    if num % 2 == 1:\n        doubled_traditional.append(num * 2)\ndoubled_comp = [num * 2 for num in numbers if num % 2 == 1]\nprint(f\"Traditional: {doubled_traditional}\")\nprint(f\"Comprehension: {doubled_comp}\")", "hints": ["List comp: [expression for item in iterable if condition]", "if condition goes at end for filtering", "Both produce same result"]}]',
'code', 15),

('60000000-0000-0000-0000-000000000006', 'Loop Patterns', 'Common loop patterns and use cases', 'intermediate', 24, 6, '00000000-0000-0000-0000-000000000006',
'[{"type": "text", "content": "Common loop patterns: sum accumulation, counting items, finding min/max, filtering data, transforming data, searching for items. Each pattern has specific use cases and best practices."}, {"type": "code", "question": "Implement common loop patterns', "starterCode": "numbers = [15, 8, 23, 4, 19, 7]\n\n# Find maximum\nmax_num = numbers[0]\nfor num in numbers:\n    if num > max_num:\n        max_num = num\n\n# Sum of even numbers\neven_sum = sum(num for num in numbers if num % 2 == 0)\n\n# Count numbers greater than 10\ncount_gt_10 = sum(1 for num in numbers if num > 10)\n\nprint(f\"Max: {max_num}, Even sum: {even_sum}, Count >10: {count_gt_10}\")", "solution": "numbers = [15, 8, 23, 4, 19, 7]\nmax_num = numbers[0]\nfor num in numbers:\n    if num > max_num:\n        max_num = num\neven_sum = sum(num for num in numbers if num % 2 == 0)\ncount_gt_10 = sum(1 for num in numbers if num > 10)\nprint(f\"Max: {max_num}, Even sum: {even_sum}, Count >10: {count_gt_10}\")", "hints": ["Initialize max with first element", "sum() with generator for efficient counting", "Generator expressions: (expr for item in iterable if condition)"]}]',
'code', 20),

('60000000-0000-0000-0000-000000000007', 'Loop Performance', "Understanding loop efficiency", 'intermediate', 20, 7, '00000000-0000-0000-0000-000000000006',
'[{"type": "text", "content": "Loop performance tips: Use list comprehensions for simple transformations, avoid modifying lists while iterating, use enumerate() to get index and value, use zip() to iterate multiple sequences together."}, {"type": "code", "question": "Use enumerate() and zip() for efficient iteration', "starterCode": "fruits = [\"apple\", \"banana\", \"cherry\"]\nprices = [1.50, 0.80, 2.30]\n\n# Using enumerate (index, value)\nfor i, fruit in enumerate(fruits):\n    print(f\"{i}: {fruit}\")\n\n# Using zip (iterate multiple lists)\nfor fruit, price in zip(fruits, prices):\n    print(f\"{fruit}: ${price:.2f}\")", "solution": "fruits = [\"apple\", \"banana\", \"cherry\"]\nprices = [1.50, 0.80, 2.30]\nfor i, fruit in enumerate(fruits):\n    print(f\"{i}: {fruit}\")\nfor fruit, price in zip(fruits, prices):\n    print(f\"{fruit}: ${price:.2f}\")", "hints": ["enumerate() gives (index, value)", "zip() stops at shortest sequence", "Both return iterators"]}]',
'code', 12),

('60000000-0000-0000-0000-000000000008', 'Advanced Iteration', 'Iterators, generators, and iteration tools', 'advanced', 32, 8, '00000000-0000-0000-0000-000000000006',
'[{"type": "text", "content": "Advanced iteration: Iterators (objects that implement __iter__ and __next__), Generators (functions with yield that produce sequences lazily), itertools module for complex iteration patterns."}, {"type": "code", "question": "Create a simple generator function', "starterCode": "def fibonacci_sequence(n):\n    \"\"\"Generate first n Fibonacci numbers\"\"\"\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b\n\n# Use the generator\nfor num in fibonacci_sequence(10):\n    print(num, end=\" \")\nprint()", "solution": "def fibonacci_sequence(n):\n    \"\"\"Generate first n Fibonacci numbers\"\"\"\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b\n\nfor num in fibonacci_sequence(10):\n    print(num, end=\" \")\nprint()", "hints": ["yield returns generator value", "Generators pause and resume state", "Multiple assignment swaps values"]}]',
'code', 20),

-- STRING OPERATIONS SECTION (8 lessons)
('70000000-0000-0000-0000-000000000001', 'String Methods', 'Essential string manipulation methods', 'intermediate', 22, 1, '00000000-0000-0000-0000-000000000007',
'[{"type": "text", "content": "String methods: .upper(), .lower(), .strip(), .lstrip(), .rstrip(), .replace(), .split(), .join(), .find(), .count(), .startswith(), .endswith(), .title(), .capitalize()."}, {"type": "code", "question": "Practice common string methods', "starterCode": "text = \"  Hello, Python Programming!  \"\n\n# Clean and transform text\nclean_text = text.strip()\nprint(f\"Cleaned: \'{clean_text}\'\")\n\n# Case operations\nprint(f\"Upper: {clean_text.upper()}\")\nprint(f\"Title: {clean_text.title()}\")\n\n# Find and replace\nprint(f\"Contains \\'Python\\': {clean_text.lower().find(\'python\') != -1}\")\nprint(f\"Replace Python with JavaScript: {clean_text.replace(\'Python\', \'JavaScript\')}\")", "solution": "text = \"  Hello, Python Programming!  \"\nclean_text = text.strip()\nprint(f\"Cleaned: \'{clean_text}\'\")\nprint(f\"Upper: {clean_text.upper()}\")\nprint(f\"Title: {clean_text.title()}\")\nprint(f\"Contains \\'Python\\': {clean_text.lower().find(\'python\') != -1}\")\nprint(f\"Replace Python with JavaScript: {clean_text.replace(\'Python\', \'JavaScript\')}\")", "hints": ["strip() removes whitespace from both ends", "find() returns -1 if not found", "title() capitalizes first letter of each word", "replace() replaces all occurrences"]}]',
'code', 15),

('70000000-0000-0000-0000-000000000002', 'String Formatting', 'Modern Python string formatting', 'intermediate', 24, 2, '00000000-0000-0000-0000-000000000007',
'[{"type": "text", "content": "String formatting methods: f-strings (Python 3.6+), .format() method, % operator (legacy). F-strings are preferred: f\"{variable}\" or f\"{expression:format}\"."}, {"type": "code", "question": "Practice f-string formatting with different types', "starterCode": "name = \"Alice\"\nage = 30\nheight = 5.7\ngpa = 3.85\n\n# Basic formatting\nprint(f\"Student: {name}, Age: {age}\")\n\n# Number formatting\nprint(f\"Height: {height:.1f} feet\")\nprint(f\"GPA: {gpa:.2f} (Percentage: {gpa*25:.1f}%)\")\n\n# Alignment and padding\nprint(f\"{name:<10} | {age:>3} | {gpa:^6}\")", "solution": "name = \"Alice\"\nage = 30\nheight = 5.7\ngpa = 3.85\nprint(f\"Student: {name}, Age: {age}\")\nprint(f\"Height: {height:.1f} feet\")\nprint(f\"GPA: {gpa:.2f} (Percentage: {gpa*25:.1f}%)\")\nprint(f\"{name:<10} | {age:>3} | {gpa:^6}\")", "hints": [":.1f formats to 1 decimal place", ":.2f formats to 2 decimal places", ":<10 left-aligns in 10 chars", ":>3 right-aligns in 3 chars"]}]',
'code', 18),

('70000000-0000-0000-0000-000000000003', 'String Slicing and Indexing', 'Extracting parts of strings', 'intermediate', 20, 3, '00000000-0000-0000-0000-000000000007',
'[{"type": "text", "content": "String slicing: string[start:stop:step]. Indexing starts at 0. Negative indices count from end. Step can be negative for reverse. Useful for extracting substrings."}, {"type": "code", "question": "Extract information from a full name string', "starterCode": "full_name = \"John Fitzgerald Kennedy\"\n\n# Extract parts using slicing and splitting\nfirst_name = full_name.split()[0]\nlast_name = full_name.split()[-1]\nmiddle_initial = full_name.split()[1][0] + \".\"\ninitials = \".join([name[0] for name in full_name.split()])\n\nprint(f\"First: {first_name}\")\nprint(f\"Last: {last_name}\")\nprint(f\"Middle Initial: {middle_initial}\")\nprint(f\"Initials: {initials}\")", "solution": "full_name = \"John Fitzgerald Kennedy\"\nfirst_name = full_name.split()[0]\nlast_name = full_name.split()[-1]\nmiddle_initial = full_name.split()[1][0] + \".\"\ninitials = \".join([name[0] for name in full_name.split()])\nprint(f\"First: {first_name}\")\nprint(f\"Last: {last_name}\")\nprint(f\"Middle Initial: {middle_initial}\")\nprint(f\"Initials: {initials}\")", "hints": ["split() breaks string into list of words", "[0] gets first item, [-1] gets last", "[0] gets first character of string", "join() connects list items with separator"]}]',
'code', 15),

('70000000-0000-0000-0000-000000000004', 'Regular Expressions Basics', 'Pattern matching in strings', 'intermediate', 28, 4, '00000000-0000-0000-0000-000000000007',
'[{"type": "text", "content": "Regular expressions (regex) for pattern matching. Import re module. Basic patterns: . (any character), ^ (start), $ (end), * (0+), + (1+), ? (0-1), [] (character set), \\d (digit), \\w (word character)."}, {"type": "code", "question": "Use regex to validate and extract data', "starterCode": "import re\n\n# Email validation\nemail_pattern = r\"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\"\nemail = \"user@example.com\"\nprint(f\"Valid email: {re.match(email_pattern, email) is not None}\")\n\n# Phone number extraction\ntext = \"Call me at 555-123-4567 or 555-987-6543\"\nphones = re.findall(r\"\\d{3}-\\d{3}-\\d{4}\", text)\nprint(f\"Phone numbers found: {phones}\")\n\n# Word boundaries\npattern = r\"\\bPython\\b\"\nsentence = \"Python is great. Python programming rocks.\"\nmatches = re.findall(pattern, sentence)\nprint(f\"Python occurrences: {len(matches)}\")", "solution": "import re\nemail_pattern = r\"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\"\nemail = \"user@example.com\"\nprint(f\"Valid email: {re.match(email_pattern, email) is not None}\")\ntext = \"Call me at 555-123-4567 or 555-987-6543\"\nphones = re.findall(r\"\\d{3}-\\d{3}-\\d{4}\", text)\nprint(f\"Phone numbers found: {phones}\")\npattern = r\"\\bPython\\b\"\nsentence = \"Python is great. Python programming rocks.\"\nmatches = re.findall(pattern, sentence)\nprint(f\"Python occurrences: {len(matches)}\")", "hints": ["re.match() checks from start", "re.findall() finds all matches", "\\b matches word boundaries", "\\d matches digits", "[...] matches character sets"]}]',
'code', 20),

('70000000-0000-0000-0000-000000000005', 'String to List Conversions', 'Splitting and joining strings', 'intermediate', 18, 5, '00000000-0000-0000-0000-000000000007',
'[{"type": "text", "content": "Converting between strings and lists: .split() breaks string into list based on delimiter, .join() combines list into string with separator. Common for parsing and data processing."}, {"type": "code", "question": "Parse CSV-like data and reconstruct it', "starterCode": "csv_data = \"John,25,New York\\nJane,30,Los Angeles\\nBob,35,Chicago\"\n\n# Parse lines and split into structured data\nlines = csv_data.strip().split(\"\\n\")\nparsed_data = []\n\nfor line in lines:\n    parts = line.split(\",\")\n    parsed_data.append({\n        \"name\": parts[0],\n        \"age\": int(parts[1]),\n        \"city\": parts[2]\n    })\n\n# Reconstruct with different format\nfor person in parsed_data:\n    formatted = f\"{person[\\\"name\\\"]} ({person[\\\"age\\\"]}) lives in {person[\\\"city\\\"]}\"\n    print(formatted)", "solution": "csv_data = \"John,25,New York\\nJane,30,Los Angeles\\nBob,35,Chicago\"\nlines = csv_data.strip().split(\"\\n\")\nparsed_data = []\nfor line in lines:\n    parts = line.split(\",\")\n    parsed_data.append({\n        \"name\": parts[0],\n        \"age\": int(parts[1]),\n        \"city\": parts[2]\n    })\nfor person in parsed_data:\n    formatted = f\"{person[\\\"name\\\"]} ({person[\\\"age\\\"]}) lives in {person[\\\"city\\\"]}\"\n    print(formatted)", "hints": ["strip() removes leading/trailing whitespace", "split() without argument splits on any whitespace", "split(\",\") splits on commas", "Convert strings to other types as needed"]}]',
'code', 15),

('70000000-0000-0000-0000-000000000006', 'Unicode and Encoding', 'Working with international text', 'intermediate', 26, 6, '00000000-0000-0000-0000-000000000007',
'[{"type": "text", "content": "Python 3 uses Unicode for strings (UTF-8 encoding by default). Can handle international characters, emojis, special symbols. Use encode() and decode() for byte conversions."}, {"type": "code", "question": "Work with Unicode characters and encoding', "starterCode": "# Unicode strings with international characters\ngreeting = \"Hello! ¡Hola! Bonjour! 你好! こんにちは! 안녕하세요! 🌍\"\nprint(f\"International greeting: {greeting}\")\n\n# Character information\nfor char in greeting[:5]:  # First 5 characters\n    print(f\"\\\"{char}\\\" - Unicode: U+{ord(char):04X}\")\n\n# String length and byte length\nprint(f\"String length: {len(greeting)} characters\")\ngreeting_bytes = greeting.encode(\'utf-8\')\nprint(f\"Byte length: {len(greeting_bytes)} bytes\")\n\n# Decode back\nprint(f\"Decoded: {greeting_bytes.decode(\'utf-8\')}\")", "solution": "greeting = \"Hello! ¡Hola! Bonjour! 你好! こんにちは! 안녕하세요! 🌍\"\nprint(f\"International greeting: {greeting}\")\nfor char in greeting[:5]:\n    print(f\"\\\"{char}\\\" - Unicode: U+{ord(char):04X}\")\nprint(f\"String length: {len(greeting)} characters\")\ngreeting_bytes = greeting.encode(\'utf-8\')\nprint(f\"Byte length: {len(greeting_bytes)} bytes\")\nprint(f\"Decoded: {greeting_bytes.decode(\'utf-8\')}\")", "hints": ["ord() gets Unicode code point", ":04X formats as 4-digit hex", "encode() converts to bytes", "decode() converts bytes back to string"]}]',
'code', 18),

('70000000-0000-0000-0000-000000000007', 'String Performance', 'Efficient string operations', 'intermediate', 22, 7, '00000000-0000-0000-0000-000000000007',
'[{"type": "text", "content": "String performance tips: Use join() instead of + for concatenation in loops, use f-strings for formatting, use .format() for complex patterns, consider list comprehensions for string transformations."}, {"type": "code", "question": "Compare string concatenation methods', "starterCode": "words = [\"Python\", \"is\", \"awesome\", \"and\", \"powerful\"]\n\n# Method 1: Inefficient (creates new string each time)\nresult1 = \"\"\nfor word in words:\n    result1 += word + \" \"\nresult1 = result1.strip()\n\n# Method 2: Efficient (join)\nresult2 = \" \".join(words)\n\n# Method 3: List comprehension for transformation\nuppercase_words = [word.upper() for word in words]\nresult3 = \" \".join(uppercase_words)\n\nprint(f\"Method 1: {result1}\")\nprint(f\"Method 2: {result2}\")\nprint(f\"Method 3: {result3}\")", "solution": "words = [\"Python\", \"is\", \"awesome\", \"and\", \"powerful\"]\nresult1 = \"\"\nfor word in words:\n    result1 += word + \" \"\nresult1 = result1.strip()\nresult2 = \" \".join(words)\nuppercase_words = [word.upper() for word in words]\nresult3 = \" \".join(uppercase_words)\nprint(f\"Method 1: {result1}\")\nprint(f\"Method 2: {result2}\")\nprint(f\"Method 3: {result3}\")", "hints": ["join() is much faster than += in loops", "List comprehensions are efficient", "Choose method based on readability and performance needs"]}]',
'code', 12),

('70000000-0000-0000-0000-000000000008', 'Advanced String Techniques', 'Advanced string manipulation patterns', 'advanced', 30, 8, '00000000-0000-0000-0000-000000000007',
'[{"type": "text", "content": "Advanced string techniques: Template strings for safe formatting, string modules for constants, textwrap for text formatting, difflib for comparing strings, unicodedata for character information."}, {"type": "code", "question": "Use string module constants and textwrap', "starterCode": "import string\nimport textwrap\n\n# String module constants\nprint(f\"Lowercase letters: {string.ascii_lowercase}\")\nprint(f\"Digits: {string.digits}\")\nprint(f\"Punctuation: {string.punctuation}\")\n\n# Generate random password-like string\nimport random\nchars = string.ascii_letters + string.digits + \"!@#$%\"\npassword = \'\'.join(random.choice(chars) for _ in range(12))\nprint(f\"Generated: {password}\")\n\n# Text wrapping\nlong_text = \"This is a very long string that needs to be wrapped to fit within a specific width for better readability in console output.\"\nwrapped = textwrap.fill(long_text, width=40)\nprint(f\"\\nWrapped text:\\n{wrapped}\")", "solution": "import string\nimport textwrap\nprint(f\"Lowercase letters: {string.ascii_lowercase}\")\nprint(f\"Digits: {string.digits}\")\nprint(f\"Punctuation: {string.punctuation}\")\nimport random\nchars = string.ascii_letters + string.digits + \"!@#$%\"\npassword = \'\'.join(random.choice(chars) for _ in range(12))\nprint(f\"Generated: {password}\")\nlong_text = \"This is a very long string that needs to be wrapped to fit within a specific width for better readability in console output.\"\nwrapped = textwrap.fill(long_text, width=40)\nprint(f\"\\nWrapped text:\\n{wrapped}\")", "hints": ["string module has useful constants", "textwrap.fill() wraps long text", "random.choice() picks random items", "List comprehensions generate sequences"]}]',
'code', 20);

SELECT 'SUCCESS: 56 lessons added! Final 4 lessons for File Operations, Error Handling, and OOP...' as message,
       COUNT(*) as total_lessons_added
FROM lessons;